services:
  postgres:
    image: postgres:16-alpine
    container_name: awesome-pizza-backend-postgres
    environment:
      POSTGRES_DB: awesome_pizza
      POSTGRES_USER: awesome_pizza
      POSTGRES_PASSWORD: awesome_pizza
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U awesome_pizza -d awesome_pizza"]
      interval: 10s
      timeout: 5s
      retries: 10

  awesome-pizza-backend-api:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: awesome-pizza-backend-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: awesome_pizza
      POSTGRES_USER: awesome_pizza
      POSTGRES_PASSWORD: awesome_pizza
      CORS_ORIGINS: http://localhost:3000
    ports:
      - "8081:8081"

volumes:
  postgres-data:
