quarkus.application.name=awesome-pizza
quarkus.http.port=8081

quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=/.*/
%prod.quarkus.http.cors.origins=${CORS_ORIGINS:http://localhost:3000}
quarkus.http.cors.methods=GET,POST,PATCH,OPTIONS
quarkus.http.cors.headers=Content-Type

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.filter=true
quarkus.swagger-ui.tags-sorter=alpha
quarkus.swagger-ui.operations-sorter=alpha

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER:user}
quarkus.datasource.password=${POSTGRES_PASSWORD:password}
quarkus.datasource.jdbc.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:awesome_pizza}

quarkus.hibernate-orm.schema-management.strategy=${ORM_MANAGEMENT_STRATEGY:none}
quarkus.hibernate-orm.log.sql=false

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migrations
