services:
  postgres:
    image: postgres:16-alpine
    container_name: awesome-pizza-postgres
    environment:
      POSTGRES_DB: awesome_pizza
      POSTGRES_USER: awesome_user
      POSTGRES_PASSWORD: awesome_user
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U awesome_pizza -d awesome_pizza"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
